version: "3.7"
services: 
    server:
        build:
            dockerfile: Dockerfile
            context: .
        env_file: .env
        depends_on:
            - database
        networks:
            - default
        ports:
            - "3000:3000"
        # networks:
        #     - backend
    database:
        image: postgres
        restart: always
        env_file: 
            - .env
        ports:
            - "5432:5432"
        volumes: 
            - data:/var/lib/postgresql/data
        networks:
            - backend
volumes:
    data:
networks:
    backend: